### ISSUE TITLE
Create legacy shim query API and wire into old visualizer

### ISSUE THREAD

**Issue by awerchniak** [awerchniak/cdk-hiscores-tracker#18]
https://www.osrs-stats-visualizer.net/ is powered by an older version of this app not defined in CDK. We could hopefully improve its performance by swapping in this back end,

API would parse correct table query from a simple regex on the format defined [here](https://github.com/awerchniak/viz_osrs/commit/c5dd2377432ac1ea9f36ebcb075f7fd4f60e49cd#diff-c478828718fc372d5d3a1e25a9aad13b8040292210214987b180da3a40d39404R89) and retrieve the appropriate data from HiScoresTable in the expected format (see `migrate_db.py`, available at 6ba57d8883e83418793abcec268eaeb37e8d5a16, for an example query). 

Once the API is implemented, it can be replaced [here](https://github.com/awerchniak/viz_osrs/commit/9f1196f2dd0f07d881a9247da7b6c0ff5bd2dc1e#diff-c478828718fc372d5d3a1e25a9aad13b8040292210214987b180da3a40d39404R15) and released on the site.

This should improve loading time for long time span requests and aggregated data will be returned,

**Comment by awerchniak** [comment]
Looks like we need this for the front end to be able to call the API: https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_apigateway/IResource.html#aws_cdk.aws_apigateway.IResource.add_cors_preflight

**Comment by awerchniak** [comment]
^using the above led to 
```
(.venv) andyw@DESKTOP-Q0LKRM6:~/code/cdk-hiscores-tracker$ cdk deploy
jsii.errors.JavaScriptError: 
  Error: Cannot call 'addMethod' on a proxying LambdaRestApi; set 'proxy' to false
      at RootResource.addMethodThrows [as addMethod] (/tmp/jsii-kernel-8egGer/node_modules/aws-cdk-lib/aws-apigateway/lib/lambda-api.js:48:11)
      at RootResource.addCorsPreflight (/tmp/jsii-kernel-8egGer/node_modules/aws-cdk-lib/aws-apigateway/lib/resource.js:136:21)
      at /tmp/tmpvh6xzk6b/lib/program.js:8248:134
      at Kernel._wrapSandboxCode (/tmp/tmpvh6xzk6b/lib/program.js:8860:24)
      at /tmp/tmpvh6xzk6b/lib/program.js:8248:107
      at Kernel._ensureSync (/tmp/tmpvh6xzk6b/lib/program.js:8841:28)
      at Kernel.invoke (/tmp/tmpvh6xzk6b/lib/program.js:8248:34)
      at KernelHost.processRequest (/tmp/tmpvh6xzk6b/lib/program.js:9757:36)
      at KernelHost.run (/tmp/tmpvh6xzk6b/lib/program.js:9720:22)
      at Immediate._onImmediate (/tmp/tmpvh6xzk6b/lib/program.js:9721:46)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 10, in <module>
    HiscoresTrackerStack(app, "HiscoresTrackerStack")
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/hiscores_tracker/hiscores_tracker_stack.py", line 25, in __init__
    atst = AggregatingTimeSeriesTable(self, "HiScoresATST")
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/hiscores_tracker/agg_time_series_table.py", line 90, in __init__
    self._query_api.root.add_cors_preflight(
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/aws_cdk/aws_apigateway/__init__.py", line 18074, in add_cors_preflight
    return typing.cast(Method, jsii.invoke(self, "addCorsPreflight", [options]))
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 143, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 355, in invoke
    response = self.provider.invoke(
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 359, in invoke
    return self._process.send(request, InvokeResponse)
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Cannot call 'addMethod' on a proxying LambdaRestApi; set 'proxy' to false
Subprocess exited with error 1
```

We could set `proxy=False`, but then we'd have to do some extra work defining where to route the API (will require a bit more reading):
```
proxy (Optional[bool]) – If true, route all requests to the Lambda Function. If set to false, you will need to explicitly define the API model using addResource and addMethod (or addProxy). Default: true
```

I also tried adding [CorsOptions](https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_apigateway/CorsOptions.html) to the [LambdaRestAPI](https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_apigateway/LambdaRestApi.html) instead:
```
        # Expose Rest API for queryer
        self._query_api = apigw.LambdaRestApi(
            self,
            "QueryHiScoresData",
            handler=queryer,
            default_cors_preflight_options=apigw.CorsOptions(
                allow_credentials=True, allow_origins=apigw.Cors.ALL_ORIGINS
            ),
        )
        self._query_api.root.add_method("GET")
```

but doing it this way, it doesn't look like the headers are present:
```
>>> r = requests.get("https://ee7wrcqwva.execute-api.us-east-1.amazonaws.com/prod/legacy?sql=SELECT+timestamp%2COverall%2CAttack%2CDefence%2CStrength%2CHitpoints%2CRanged%2CPrayer%2CMagic%2CCooking%2CWoodcutting%2CFletching%2CFishing%2CFiremaking%2CCrafting%2CSmithing%2CMining%2CHerblore%2CAgility%2CThieving%2CSlayer%2CFarming%2CRunecrafting%2CHunter%2CConstruction+FROM+skills.experience+WHERE+player%3D%27ElderPlinius%27+AND+timestamp+%3E+%272021-12-26+00%3A00%3A00%27+AND+timestamp+%3C+%272022-01-02+23%3A59%3A59%27+ORDER+BY+timestamp+ASC")
>>> r.headers
{'Content-Type': 'application/json', 'Content-Length': '1788', 'Connection': 'keep-alive', 'Date': 'Mon, 03 Jan 2022 01:41:11 GMT', 'x-amzn-RequestId': 'c861869d-83bb-4b27-8b02-9cc974a82a5e', 'x-amz-apigw-id': 'LWIYmHlRIAMF1nw=', 'X-Amzn-Trace-Id': 'Root=1-61d25436-5d4463aa011431d3653b69b6;Sampled=0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 e329cb97e195e238d2d961aa95a36a4a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'PHL50-C1', 'X-Amz-Cf-Id': 'RghMl_fQ6VfjMKG7k6OJ5UhZ0oqedVmIw3J9gaS74H0L5pzufefUAg=='}
```

Might be easier to handle this on the front-end side; will consult Trevor and see what he thinks before exploring further

**Comment by awerchniak** [comment]
Dev endpoint on visualizer app: https://dev.dvu7w83da6q94.amplifyapp.com/

The error message I was attempting to address above is:
```
Access to fetch at 'https://ee7wrcqwva.execute-api.us-east-1.amazonaws.com/prod/legacy?sql=SELECT+timestamp%2COverall%2CAttack%2CDefence%2CStrength%2CHitpoints%2CRanged%2CPrayer%2CMagic%2CCooking%2CWoodcutting%2CFletching%2CFishing%2CFiremaking%2CCrafting%2CSmithing%2CMining%2CHerblore%2CAgility%2CThieving%2CSlayer%2CFarming%2CRunecrafting%2CHunter%2CConstruction+FROM+skills.experience+WHERE+player%3D%27ElderPlinius%27+AND+timestamp+%3E+%272021-12-26+00%3A00%3A00%27+AND+timestamp+%3C+%272022-01-02+23%3A59%3A59%27+ORDER+BY+timestamp+ASC' from origin 'https://dev.dvu7w83da6q94.amplifyapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
